# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG Sevilla "
email: "contacto@gdgsevilla.com"
description: "Sesiones para aprender juntos"
baseurl: ""
url: "http://www.gdgsevilla.com/"
googleAnalyticsTrackingId: "UA-61791444-1"
#googleAnalyticsTrackingId: "UA-64592177-1"
googleAnalyticsSiteUrl: "gdgsevilla.github.io"
siteVerification: "Ay_dR1jYty54q786TpnGMfFLKf0FpgroITTnw1TmTv4"


# Organizer Info
organizerName: "GDG Sevilla"
organizerAlternateName: "Google Developer Group Sevilla"
organizerDescription: "Grupo sin ánimo de lucro cuyo objetivo es el de aprender e intercambiar conocimientos y experiencias acerca de las tecnologías proporcionadas por Google."
organizerEmail: "contacto@gdgsevilla.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://plus.google.com/117186888160178861350/about"

# Head
metaKeywords: "android, evento, gdg, google, developers, sevilla, desarrollo, event"
twitterAccount: "@GDGSevilla"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/#tickets", text: "Entradas"}
 - {permalink: "/#aboutSDC", text: "¿En qué consiste?"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/#location-map", text: "¿Dónde?"}
# - {permalink: "/#partners", text: "Organizan"}

# Hero Block
heroImage: "hero.jpg"
heroMain: "Sevilla Developers Conf 2 #SVQDC"
heroTitle: "Porque aquí no se hace nada de <typeout>"
eventDate: "Sábado, 12 de Marzo, 2016"
typeoutTextValues: '"Java", "Android", "PHP", "Ruby", "JavaScript", "Python", "WordPress", "Xamarin", ".NET", "Kotlin", "Angular", "Perl", "Go", "Integración Contínua", "DevOps"'
typeoutFallback: "tecnología"
heroButtons:
   - {permalink: "/#tickets", text: "¡Entradas agotadas!"}


# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Nuestros ponentes"
rockstarSpeakersButtonText: "Ver más"

# Speakers List Block
showSessions: true


# Location Block
locationBlockTitle: "Dónde?"
eventLocationName: "Bitnami"
eventLocationLink: "http://bitnami.com/"
eventStreetAddress: "Avenida República Argentina, 31B"
eventAddressLocality: "Sevilla"
eventAddressLocalityRegion: "Sevilla"
eventPostalCode: "41011"
eventAddressCountry: "España"
eventStartTime: "2016-03-12T10:00"
eventDoorTime: "09:30"
eventEndTime: "2016-03-12T18:00"
readableDate: "Sábado 12 de Marzo 2016"
eventPlaceCoordinates: "37.377736,-6.001971"
mapCenterCoordinates: "37.377736,-6.001971"
mapMobileCenterCoordinates: "37.377736,-6.001971"

# Partners Block
organizersTitle: "Organizan"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Únete a nosotros"
c4sponsorsUrl: "mailto:contacto@gdgsevilla.com"

# Tickets Block
tweetsFeedImage: "twitter-feed.png"
ticketsTitle: "Entradas"
ticketsInfo: "La entrada solo es válida para la sesión indicada"
ticketsOffers:

##TODO: entradas 2
-
  name: "Early Bird"
  price: "5"
  priceCurrency: "EUR"
  ticketsNumber: "25"
  buyButtonLink: "https://www.ticketea.com/entradas-charla-svqdc/"
  buyButtonText: "Aprovecha!"
  additionalInfo: ""
  ticketContentList: [ "A la mitad de precio", "Solo tienes unos pocos días"]
  validFrom: "2015-10-01T10:00"
  validThrough: "2015-10-11T23:59"
  soldOut: true
  soldOutText: "Agotadas!"
  ribbon: "Bitnami"
  featured: true

##TODO: entradas 2
-
  name: "Last chance"
  price: "10"
  priceCurrency: "EUR"
  ticketsNumber: "25"
  buyButtonLink: "https://www.ticketea.com/entradas-charla-svqdc/"
  buyButtonText: "Es tu ultima oportunidad"
  additionalInfo: ""
  ticketContentList: [ "Para los rezagados", "No te quedes sin tuya"]
  validFrom: "2015-10-12T00:00"
  validThrough: "2015-10-16T23:59"
  disabled: true
  soldOut: true
  soldOutText: "Agotadas!"


# Footer
socialLinks:
 - {link: "https://plus.google.com/117186888160178861350/about", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGSevilla", icon: "twitter"}
 - {link: "https://www.facebook.com/pages/Sevilla-GDG/198294916872055", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Enlaces"
  links:
   - {link: "http://www.meetup.com/PHP-Sevilla", text: "PHP Sevilla"}
   - {link: "http://http://www.meetup.com/SVQJUG", text: "SVQ JUG"}
   - {link: "https://plus.google.com/117186888160178861350/", text: "GDG Sevilla"}
   - {link: "https://developers.google.com", text: "Google Developers"}

 -
  title: "Contactar"
  links:
   - {link: "mailto:contacto@gdgsevilla.com", text: "contacto@gdgsevilla.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de Conducta"}

# About
teamBlockTitle: "¿Qué es SevillaDeveloperConf?"
aboutIt: "<p>
¡Volvemos a la carga con el escaparate de las distintas comunidades tecnológicas de Sevilla!

Ya habeis comprobado que no hemos cumplido a raja tabla la trimestralidad de la iniciativa, pero para compensarlo hemos
estado revisando vuestras respuestas a la última encuesta y hemos introducido algunos cambios: aún más contenido y más
tiempo para poder socializar (paa no morir por sobredosis de información).

En esta ocasión contamos con la colaboración de la <a href='https://www.eoi.es/es/eoi-sevilla'>Escuela de Organización Industrial</a> en
cuyas instalaciones realizaremos este evento.

Echale un vistazo a nuestros ponentes o al programa para saber más sobre los contenidos de esta edición

"


# Logistics Find Way Block
findWayTitle: "Cómo llegar"
findWayDistance: "Distancia"
findWayDriving: "En Coche"
findWayWalking: "Andando"
findWayBicycling: "En Bicicleta"
findWayTransit: "Autobus"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

##TODO: Cambiar el icono del gdg 2015
##TODO: Add it to dev calendar, sdc calendar
##TODO: Add it to meetups (include link to ticketea)
