# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG Sevilla "
email: "contacto@gdgsevilla.com"
description: "Sesiones para aprender juntos"
baseurl: ""
url: "http://www.gdgsevilla.com/"
googleAnalyticsTrackingId: "UA-61791444-1"
#googleAnalyticsTrackingId: "UA-64592177-1"
googleAnalyticsSiteUrl: "gdgsevilla.github.io"
siteVerification: "Ay_dR1jYty54q786TpnGMfFLKf0FpgroITTnw1TmTv4"


# Organizer Info
organizerName: "GDG Sevilla"
organizerAlternateName: "Google Developer Group Sevilla"
organizerDescription: "Grupo sin ánimo de lucro cuyo objetivo es el de aprender e intercambiar conocimientos y experiencias acerca de las tecnologías proporcionadas por Google."
organizerEmail: "contacto@gdgsevilla.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://plus.google.com/117186888160178861350/about"

# Head
metaKeywords: "android, evento, gdg, google, developers, sevilla, desarrollo, event"
twitterAccount: "@GDGSevilla"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/#tickets", text: "Entradas"}
 - {permalink: "/#aboutSDC", text: "¿En qué consiste?"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/#location-map", text: "¿Dónde?"}
# - {permalink: "/#partners", text: "Organizan"}

# Hero Block
heroImage: "hero.jpg"
heroMain: "Sevilla Developers Conf #SVQDC"
heroTitle: "Porque aquí no se hace nada de <typeout>"
eventDate: "Sábado, 17 de Octubre, 2015"
typeoutTextValues: '"Java", "Android", "PHP", "Ruby", "JavaScript", "Python", "WordPress", "Xamarin", ".NET", "Kotlin", "Angular", "Perl", "Go", "Integración Contínua", "DevOps"'
typeoutFallback: "tecnología"
heroButtons:
   - {permalink: "/#tickets", text: "Consigue tu entrada"}


# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Nuestros ponentes"
rockstarSpeakersButtonText: "Ver más"

# Speakers List Block
showSessions: true


# Location Block
locationBlockTitle: "Dónde?"
eventLocationName: "Bitnami"
eventLocationLink: "http://bitnami.com/"
eventStreetAddress: "Avenida República Argentina, 31B"
eventAddressLocality: "Sevilla"
eventAddressLocalityRegion: "Sevilla"
eventPostalCode: "41011"
eventAddressCountry: "España"
eventStartTime: "2015-10-17T10:00"
eventDoorTime: "10:00"
eventEndTime: "2015-10-17T14:30"
readableDate: "Sábado 17 de Octubre 2015"
eventPlaceCoordinates: "37.377736,-6.001971"
mapCenterCoordinates: "37.377736,-6.001971"
mapMobileCenterCoordinates: "37.377736,-6.001971"

# Partners Block
organizersTitle: "Organizan"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Únete a nosotros"
c4sponsorsUrl: "mailto:contacto@gdgsevilla.com"

# Tickets Block
tweetsFeedImage: "twitter-feed.png"
ticketsTitle: "Entradas"
ticketsInfo: "La entrada solo es válida para la sesión indicada"
ticketsOffers:
-
  name: "Early Bird"
  price: "5"
  priceCurrency: "EUR"
  ticketsNumber: "25"
  buyButtonLink: "https://www.ticketea.com/entradas-charla-svqdc/"
  buyButtonText: "Aprovecha!"
  additionalInfo: ""
  ticketContentList: [ "A la mitad de precio", "Solo tienes unos pocos días"]
  validFrom: "2015-10-01T10:00"
  validThrough: "2015-10-11T23:59"
  soldOut: false
  soldOutText: "Agotadas!"
  ribbon: "Bitnami"
  featured: true


-
  name: "Last chance"
  price: "10"
  priceCurrency: "EUR"
  ticketsNumber: "25"
  buyButtonLink: "https://www.ticketea.com/entradas-charla-svqdc/"
  buyButtonText: "Es tu ultima oportunidad"
  additionalInfo: ""
  ticketContentList: [ "Para los rezagados", "No te quedes sin tuya"]
  validFrom: "2015-10-12T00:00"
  validThrough: "2015-10-16T23:59"
  disabled: true
  soldOut: false
  soldOutText: "Agotadas!"


# Footer
socialLinks:
 - {link: "https://plus.google.com/117186888160178861350/about", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGSevilla", icon: "twitter"}
 - {link: "https://www.facebook.com/pages/Sevilla-GDG/198294916872055", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Enlaces"
  links:
   - {link: "http://www.meetup.com/PHP-Sevilla", text: "PHP Sevilla"}
   - {link: "http://http://www.meetup.com/SVQJUG", text: "SVQ JUG"}
   - {link: "https://plus.google.com/117186888160178861350/", text: "GDG Sevilla"}
   - {link: "https://developers.google.com", text: "Google Developers"}

 -
  title: "Contactar"
  links:
   - {link: "mailto:contacto@gdgsevilla.com", text: "contacto@gdgsevilla.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de Conducta"}

# About tv
teamBlockTitle: "¿Qué es SevillaDeveloperConf?"
aboutIt: "<p>
Aprovechando que el objetivo de este <a href='https://developers.google.com/events/devfest'>DevFest</a> es fomentar la colaboración con otras comunidades, hemos aprovechado para organizar un evento de medio día con
algunas de las comunidades que se mueven en la ciudad.
En esta edición tenemos a la gente de <a href='http://www.meetup.com/PHP-Sevilla'>PHPSevilla</a>, <a href='http://http://www.meetup.com/SVQJUG'>SVQJug</a> y GDGSevilla y además de contar con la increible colaboración de
Bitnami.
 Queremos convertir esto en un evento trimestral e intentar invitar al mayor número de comunidades de ahí fuera, para que podamos cambiar la percepción de las cosas que pasan en Sevilla con ayuda de todos. Así que si
 aún no nos hemos puesto en contacto con vuestra comunidad, mandadnos un correo y para las proximas ediciones lo solucionaremos.
 </p><p>Si os preguntais el por qué del nombre, hemos querido usar uno que fuera lo más inclusivo en cuanto a tecnologias y el <a href='https://www.facebook.com/groups/sevilladevelopers/'>grupo</a> que nació en Facebook
 nos pareció el más idóneo.
 </p><p>Echadle un vistazo a las charlas y no os arrepentireis de venir.
</p>"

# About concurso
statisticBlockImage: "statistic.jpg"
concursoBlockTitle: "Concurso"
aboutConcurso: "En el concurso pueden participar cualquiera de los <span class='negrita'>asistentes a los Garages</span>, en equipos de dos personas, que deberán desarrollar y publicar antes de la última sesión una
aplicación
Android TV nativa (Java) que haga uso como mínimo de una de las funcionalidades de la Leanback Library. Como los GDG Garages son espacios para que la gente puede cacharrear con diferentes tecnologías, vamos a fomentar que los asistentes que no participen en el concurso puedan ayudar a cualquiera de los equipos (incluso a más de uno) de forma puntual. ¡Y con premio!

          Entre todos los participantes locales a un GDG, y <span class='negrita'>siempre y cuando las aplicaciones cumplan los requisitos y un mínimo de calidad, se escogerá un equipo ganador que se cuyos integrantes se
           llevarán un Nexus Player cada uno.</span> Además, <span class='negrita'>de entre todos los demás asistentes al Garage que hayan ayudado puntualmente al equipo ganador, se sorteará entre un par de Chromecasts
           .</span>

          ¡Pero la cosa no acaba aquí! <span class='negrita'>De entre todos los ganadores locales de los GDGs participantes, se seleccionarán tres candidatos a la final nacional, que tendrá lugar durante el DevFest
          Barcelona el 2 de Octubre. Los gastos de desplazamiento y alojamiento de estas personas estarán cubiertos,</span> y además el equipo ganador de la final nacional se llevará un par de tickets a cualquier
          conferencia de desarrolladores que quieran (con un máximo de 900 $ y que se puedan conseguir, que el Google I/O está así como un poco complicadete): Devvox, Droidcon, lo que sea!

          Dado que este concurso lo organizamos desde el GDG Spain de forma totalmente altruista (no ganamos nada y encima ponemos tiempo), por lo general no vamos a aceptar reclamaciones de ningún tipo. El código, la
           app, la idea, y en general todo lo que produzcáis es vuestro, pero nosotros nos reservamos la potestad de hacer cualquier aclaración a las normas que hemos expuesto. En general tiraremos
            de
           sentido
           común y todo se hará público y con fair play, y esperamos que vosotros nos ayudéis con la misma actitud."


# Logistics Find Way Block
findWayTitle: "Cómo llegar"
findWayDistance: "Distancia"
findWayDriving: "En Coche"
findWayWalking: "Andando"
findWayBicycling: "En Bicicleta"
findWayTransit: "Autobus"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false
