# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Android TV Garage "
email: "contacto@gdgsevilla.com"
description: "Sesiones para aprender juntos"
baseurl: ""
url: "http://http://www.gdgsevilla.com/"
googleAnalyticsTrackingId: "UA-61791444-1"
#googleAnalyticsTrackingId: "UA-64592177-1"
googleAnalyticsSiteUrl: "gdgsevilla.github.io"
siteVerification: "Ay_dR1jYty54q786TpnGMfFLKf0FpgroITTnw1TmTv4"


# Organizer Info
organizerName: "GDG Sevilla"
organizerAlternateName: "Google Developer Group Sevilla"
organizerDescription: "Grupo sin ánimo de lucro cuyo objetivo es el de aprender e intercambiar conocimientos y experiencias acerca de las tecnologías proporcionadas por Google."
organizerEmail: "contacto@gdgsevilla.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://plus.google.com/117186888160178861350/about"

# Head
metaKeywords: "android, evento, gdg, google, android tv, developers, sevilla, desarrollo, event"
twitterAccount: "@GDGSevilla"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/#tickets", text: "Entradas"}
 - {permalink: "/#aboutTv", text: "¿En qué consiste?"}
 - {permalink: "/#aboutConcurso", text: "Concurso"}
 - {permalink: "/#location-map", text: "¿Dónde?"}
 - {permalink: "/#partners", text: "Organizan"}
 - {permalink: "/normas/", text: "Normas"}
bottomNavigationLinks:
 - {link: "https://www.ticketea.com/android-tv-garage/", text: "Entradas"}
rightNavigationButtons:
 - {link: "https://www.ticketea.com/android-tv-garage/", text: "Entradas"}

# Hero Block
heroImage: "hero.jpg"
#heroTitle: "Android Tv Garage"
#eventDate: "4 de Julio, 2015"

# About Block
aboutTitle: "¿Qué es Android Tv Garage?"
aboutBlock:
 - {title: "Charlas", image: "conference.jpg", text: "Pasa el día aprendiendo de los mejores" }
 - {title: "Talleres", image: "workshop.png", text: "Incluidos en la agenda podras participar en talleres sobre elementos concretos de Android" }
 - {title: "Comunidad", image: "community.png", text: "Charla con los ponentes y otros miembros del sector" }

# Location Block
locationBlockTitle: "Dónde?"
eventLocationName: "Espacio res"
eventLocationLink: "http://espaciores.org/"
eventStreetAddress: "Avenida República Argentina, 25, planta 9"
eventAddressLocality: "Sevilla"
eventAddressLocalityRegion: "Sevilla"
eventPostalCode: "41011"
eventAddressCountry: "España"
eventStartTime: "2015-06-04T10:30"
eventDoorTime: "10:30"
eventEndTime: "2015-06-04T13:30"
eventPlaceCoordinates: "37.377736,-6.001971"
mapCenterCoordinates: "37.377736,-6.001971"
mapMobileCenterCoordinates: "37.377736,-6.001971"

# Venue Block
venueBlockTitle: "Espacio res"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Espacio res"
venueFeatures: ["6 magnificas terrazas", "Amplio espacio para los asistentes", "Muy bien comunicado"]

# Partners Block
organizersTitle: "Organizan"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Únete a nosotros"
c4sponsorsUrl: "mailto:contacto@gdgsevilla.com"

# Tickets Block
tweetsFeedImage: "twitter-feed.png"
ticketsTitle: "Entrada"
ticketsInfo: "La entrada solo es válida para la sesión indicada"
ticketsOffers:
-
  name: "Community"
  price: "Grátis"
  priceCurrency: "EUR"
  ticketsNumber: "40"
  buyButtonLink: "https://www.ticketea.com/android-tv-garage/"
  buyButtonText: "Consigue la tuya"
  additionalInfo: ""
  ticketContentList: [ "Sabado 4 de Julio, 10:30 - 13:30", "La entrada solo es válida para la sesión indicada", "Solo 40 plazas"]
  validFrom: "2015-04-16T10:00"
  validThrough: "2015-05-12T23:59"
  disabled: false
  soldOut: false
  soldOutText: "Agotadas!"
  featured: true

# Footer
socialLinks:
 - {link: "https://plus.google.com/117186888160178861350/about", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGSevilla", icon: "twitter"}
 - {link: "https://www.facebook.com/pages/Sevilla-GDG/198294916872055", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Enlaces"
  links:
   - {link: "https://plus.google.com/117186888160178861350/", text: "GDG Sevilla"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contactar"
  links:
   - {link: "mailto:contacto@gdgsevilla.com", text: "contacto@gdgsevilla.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de Conducta"}

# About tv
teamBlockTitle: "¿Qué es Android TV Garage?"
aboutIt: "El Google I/O siempre presenta novedades, también para los GDGs. A raíz del último en Mayo de este año, hemos decidido introducir en España un nuevo formato de evento conocido como GDG Garage,
 en los
cuales vamos a probar nuevas tecnologías y puede que hasta vuelvas a casa con un nuevo dispositivo ;)

          Los Garage son unas jornadas tecnológicas con el objetivo de profundizar en una tecnología en particular, pero en las cuales iremos aprendiendo desarrollando directamente durante la sesión según los intereses de cada uno. No hay profesores ni mentores, tan solo un grupo de gente con ganas de hacer cosas.

          Para poder dar a conocer el formato de una forma sencilla, los GDGs españoles hemos planeado hacer una serie de Garages durante los meses de Junio a Septiembre centrados especialmente en Android TV. Contaremos con algunos dispositivos para poder probar, así como con materiales didácticos facilitados por Google para poder aprender esta tecnología a base de la prueba y error.

          Además, aquellos que lo deseen, se podrán apuntar al concurso de aplicaciones nativas para Android TV (Java) que se estará abierto sólo para los participantes de los GDG Garage (os daremos más información del concurso a parte). Incluso si no participas en el concurso pero ayudas a los concursantes durante los Garages, puedes igualmente conseguir un nuevo dispositivo ;)

          ¿Quién quiere playa con este planazo? ;)"

# About concurso
statisticBlockImage: "statistic.jpg"
concursoBlockTitle: "Concurso"
aboutConcurso: "En el concurso pueden participar cualquiera de los <span class='negrita'>asistentes a los Garages</span>, en equipos de dos personas, que deberán desarrollar y publicar antes de la última sesión una
aplicación
Android TV nativa (Java) que haga uso como mínimo de una de las funcionalidades de la Leanback Library. Como los GDG Garages son espacios para que la gente puede cacharrear con diferentes tecnologías, vamos a fomentar que los asistentes que no participen en el concurso puedan ayudar a cualquiera de los equipos (incluso a más de uno) de forma puntual. ¡Y con premio!

          Entre todos los participantes locales a un GDG, y <span class='negrita'>siempre y cuando las aplicaciones cumplan los requisitos y un mínimo de calidad, se escogerá un equipo ganador que se cuyos integrantes se
           llevarán un Nexus Player cada uno.</span> Además, <span class='negrita'>de entre todos los demás asistentes al Garage que hayan ayudado puntualmente al equipo ganador, se sorteará entre un par de Chromecasts
           .</span>

          ¡Pero la cosa no acaba aquí! <span class='negrita'>De entre todos los ganadores locales de los GDGs participantes, se seleccionarán tres candidatos a la final nacional, que tendrá lugar durante el DevFest
          Barcelona el 2 de Octubre. Los gastos de desplazamiento y alojamiento de estas personas estarán cubiertos,</span> y además el equipo ganador de la final nacional se llevará un par de tickets a cualquier
          conferencia de desarrolladores que quieran (con un máximo de 900 $ y que se puedan conseguir, que el Google I/O está así como un poco complicadete): Devvox, Droidcon, lo que sea!

          Dado que este concurso lo organizamos desde el GDG Spain de forma totalmente altruista (no ganamos nada y encima ponemos tiempo), por lo general no vamos a aceptar reclamaciones de ningún tipo. El código, la
           app, la idea, y en general todo lo que produzcáis es vuestro, pero nosotros nos reservamos la potestad de hacer cualquier aclaración a las normas que hemos expuesto. En general tiraremos
            de
           sentido
           común y todo se hará público y con fair play, y esperamos que vosotros nos ayudéis con la misma actitud."


# Logistics Find Way Block
findWayTitle: "Cómo llegar"
findWayDistance: "Distancia"
findWayDriving: "En Coche"
findWayWalking: "Andando"
findWayBicycling: "En Bicicleta"
findWayTransit: "Autobus"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false