# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "SevillaDevelopersConf "
email: "contacto@sevilladevelopers.com"
description: "Sesiones para aprender juntos"
baseurl: ""
url: "http://www.sevilladevelopers.com/"
googleAnalyticsTrackingId: "UA-61791444-1"
#googleAnalyticsTrackingId: "UA-64592177-1"
googleAnalyticsSiteUrl: "gdgsevilla.github.io"
siteVerification: "Ay_dR1jYty54q786TpnGMfFLKf0FpgroITTnw1TmTv4"


# Organizer Info
organizerName: "GDG Sevilla"
organizerAlternateName: "Google Developer Group Sevilla"
organizerDescription: "Grupo sin ánimo de lucro cuyo objetivo es el de aprender e intercambiar conocimientos y experiencias acerca de las tecnologías proporcionadas por Google."
organizerEmail: "contacto@gdgsevilla.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://plus.google.com/117186888160178861350/about"

# Head
metaKeywords: "android, evento, gdg, google, developers, sevilla, desarrollo, event"
twitterAccount: "@GDGSevilla"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/#tickets", text: "Entradas"}
 - {permalink: "/#aboutSDC", text: "¿En qué consiste?"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/#location-map", text: "¿Dónde?"}
# - {permalink: "/#partners", text: "Organizan"}

# Hero Block
heroImage: "hero.jpg"
heroMain: "Sevilla Developers Conf 2 #SVQDC"
heroTitle: "Porque aquí <b>sigue</b> sin hacerse nada de <typeout>"
eventDate: "Sábado, 12 de Marzo, 2016"
typeoutTextValues: '"Java", "Go", "Android", "PHP", "Swift", "Ruby", "JavaScript", "Python", "WordPress", "Xamarin", ".NET", "Kotlin", "Angular", "Perl", "Integración Contínua", "DevOps"'
typeoutFallback: "tecnología"
heroButtons:
   - {permalink: "/#tickets", text: "Entradas"}


# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 5
rockstarSpeakersTitle: "Nuestros ponentes"
rockstarSpeakersButtonText: "Más información"

# Speakers List Block
showSessions: true


# Location Block
locationBlockTitle: "Dónde?"
eventLocationName: "Escuela de Organización industrial Sevilla"
eventLocationLink: "https://www.eoi.es/es/eoi-sevilla"
eventStreetAddress: "Calle Leonardo da Vinci, 12"
eventAddressLocality: "Isla de la Cartuja"
eventAddressLocalityRegion: "Sevilla"
eventPostalCode: "41092"
eventAddressCountry: "España"
eventStartTime: "2016-03-12T09:30"
eventDoorTime: "09:30"
eventEndTime: "2016-03-12T18:00"
readableDate: "Sábado 12 de Marzo 2016"
eventPlaceCoordinates: "37.404639,-6.0087697"
mapCenterCoordinates: "37.404639,-6.0087697"
mapMobileCenterCoordinates: "37.404639,-6.0087697"

# Partners Block
organizersTitle: "Organizan"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Únete a nosotros"
c4sponsorsUrl: "mailto:contacto@sevilladevelopers.com"

# Tickets Block
tweetsFeedImage: "twitter-feed.png"
ticketsTitle: "Entradas"
ticketsInfo: "La entrada solo es válida para la sesión indicada"
ticketsOffers:

-
  name: "Early Bird"
  price: "5"
  priceCurrency: "EUR"
  ticketsNumber: "75"
  buyButtonLink: "https://www.ticketea.com/entradas-charla-sevilladevelopersconf/"
  buyButtonText: "Aprovecha!"
  additionalInfo: ""
  ticketContentList: [ "Vuelven por petición popular", "A la mitad de precio", "¡Sólo hasta el 29 de Febrero!"]
  disabled: true
  validFrom: "2016-02-15T12:30"
  validThrough: "2016-02-29T23:59"
  soldOut: true
  soldOutText: "Agotadas!"
  ribbon: "EOI"

-
  name: "Last chance"
  price: "10"
  priceCurrency: "EUR"
  ticketsNumber: "75"
  buyButtonLink: "https://www.ticketea.com/entradas-charla-sevilladevelopersconf/"
  buyButtonText: "Es tu última oportunidad"
  additionalInfo: ""
  ticketContentList: [ "Mantenemos el precio de la edición anterior","Para los rezagados", "No te quedes sin la tuya"]
  validFrom: "2016-03-01T00:00"
  validThrough: "2016-03-11T17:00"
  disabled: false
  soldOut: false
  soldOutText: "Agotadas!"
  featured: true


# Footer
socialLinks:
 - {link: "https://plus.google.com/117186888160178861350/about", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGSevilla", icon: "twitter"}
 - {link: "https://www.facebook.com/pages/Sevilla-GDG/198294916872055", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Enlaces"
  links:
   - {link: "http://www.meetup.com/PHP-Sevilla", text: "PHP Sevilla"}
   - {link: "http://http://www.meetup.com/SVQJUG", text: "SVQ JUG"}
   - {link: "https://plus.google.com/117186888160178861350/", text: "GDG Sevilla"}
   - {link: "http://nscoder-sev.tumblr.com/", text: "NSCoder Night Sevilla"}

 -
  title: "Contactar"
  links:
   - {link: "mailto:contacto@sevilladevelopers.com", text: "contacto@sevilladevelopers.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de Conducta"}

 -
  title: "Ediciones previas"
  links:
   - {link: "http://old.sevilladevelopers.com", text: "Primera edición"}

# About
aboutBlockTitle: "¿Qué es SevillaDeveloperConf?"
aboutCatch: "¡Volvemos a la carga con el escaparate de las distintas comunidades tecnológicas de Sevilla!"
aboutIt: "Ya habeis comprobado que no hemos cumplido a raja tabla la trimestralidad de la iniciativa, pero para compensarlo hemos
estado revisando vuestras respuestas a la última encuesta y hemos introducido algunos cambios: aún más contenido y más
tiempo para poder socializar (para no morir por sobredosis de información)."


# Logistics Find Way Block
findWayTitle: "Cómo llegar"
findWayDistance: "Distancia"
findWayDriving: "En Coche"
findWayWalking: "Andando"
findWayBicycling: "En Bicicleta"
findWayTransit: "Autobus"
logisticsMapCenterCoordinates: "40.121684,-8.203308"
logisticsMapMobileCenterCoordinates: "40.121684,-8.203308"
logisticsMapAutoDirections: false