# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Android Xtended"
email: "contacto@androidxtended.com"
description: "Un dia entero para compartir y aprender sobre Android"
baseurl: ""
url: "http://www.androidxtended.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-61791444-1"
googleAnalyticsSiteUrl: "www.androidXtended.com"
siteVerification: "Ay_dR1jYty54q786TpnGMfFLKf0FpgroITTnw1TmTv4"

# Organizer Info
organizerName: "GDG Sevilla"
organizerAlternateName: "Google Developer Group Sevilla"
organizerDescription: "Grupo sin ánimo de lucro cuyo objetivo es el de aprender e intercambiar conocimientos y experiencias acerca de las tecnologías proporcionadas por Google."
organizerEmail: ""
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://plus.google.com/117186888160178861350/about"

# Head
metaKeywords: "android, evento, gdg, google, android, developers, sevilla, desarrollo, event"
twitterAccount: "@GDGSevilla"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Ponentes"}
 - {permalink: "/team/", text: "Equipo"}
 - {permalink: "/logistics/", text: "Prepárate"}
bottomNavigationLinks:
 - {link: "https://www.ticketea.com/androidxtended/", text: "Entradas"}
rightNavigationButtons:
 - {link: "https://www.ticketea.com/androidxtended/", text: "Entradas"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Android Xtended"
eventDate: "16 de Mayo, 2015"
heroButtons:
 - {permalink: "/#tickets", text: "Consigue tu entrada"}

# About Block
aboutTitle: "Qué es Android Xtended"
aboutBlock:
 - {title: "Charlas", image: "conference.jpg", text: "Pasa el día aprendiendo de los mejores" }
 - {title: "Talleres", image: "workshop.png", text: "Incluidos en la agenda podras participar en talleres sobre elementos concretos de Android" }
 - {title: "Comunidad", image: "community.png", text: "Charla con los ponentes y otros miembros del sector" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "100", specialCharacter: "+", info: "asistentes", detail: "de toda Andalucia"}
 - {count: "12", specialCharacter: "+", info: "horas", detail: "de toneladas de información"}
 - {count: "5", specialCharacter: "+", info: "ponentes", detail: "de aqui y de allí"}

# Latest News Block
latestNewsTitle: "Últimas noticias"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 5
rockstarSpeakersTitle: "Nuestros ponentes"
rockstarSpeakersButtonText: "Ver más"

# Location Block
locationBlockTitle: "Dónde?"
eventLocationName: "Espacio res"
eventLocationLink: "http://espaciores.org/"
eventStreetAddress: "Avenida República Argentina, 25"
eventLocationName2: "Bitnami"
eventLocationLink2: "http://bitnami.com/"
eventStreetAddress2: "Avenida República Argentina, 31B"
eventAddressLocality: "Sevilla"
eventAddressLocalityRegion: "Sevilla"
eventPostalCode: "41011"
eventAddressCountry: "España"
eventStartTime: "2015-05-16T9:30"
eventDoorTime: "09:30"
eventEndTime: "2015-05-16T21:00"
eventPlaceCoordinates: "37.377736,-6.001971"
mapCenterCoordinates: "37.377736,-6.001971"
mapMobileCenterCoordinates: "37.377736,-6.001971"

# Venue Block
venueBlockTitle: "Sede Espacio res"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Espacio res"
venueFeatures: ["6 magnificas terrazas", "Amplio espacio para los asistentes", "Muy bien comunicado"]

# Venue2 Block
venueBlockTitle2: "Sede Bitnami"
venueBigImage2: "venue_02.jpg"
venueSmallImage12: "venue_12.jpg"
venueSmallImage22: "venue_22.jpg"
venueSmallImage32: "venue_32.jpg"
venueTitle2: "Bitnami"
venueFeatures2: ["makes it incredibly easy to deploy apps with native installers",  "as virtual machines, or in the cloud", " y desde Sevilla!"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.png"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "AndroidXtended"
twitterFeed: "http://www.androidxtended.com/tweetledee/searchjson.php?q=androidxtd+OR+androidxtnd+OR+androidxtended+OR+androidxtened"

# Partners Block
organizersTitle: "Organizan"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Únete a nosotros"
c4sponsorsUrl: "mailto:contacto@androidXtended.com"

# Tickets Block
ticketsTitle: "Precio"
ticketsInfo: "El ticket te da acceso a todas las charlas y talleres."
ticketsOffers:
-
  name: "Xtended"
  price: "10"
  priceCurrency: "EUR"
  ticketsNumber: "40"
  buyButtonLink: "https://www.ticketea.com/androidxtended/"
  buyButtonText: "Comprar"
  additionalInfo: ""
  ticketContentList: ["Accede a todas las charlas y talleres", "Conoce a otros profesionales del sector", "Solo 40 plazas en total"]
  validFrom: "2015-04-16T10:00"
  validThrough: "2015-05-12T23:59"
  disabled: false
  soldOut: true
  soldOutText: "Agotadas!"

-
  name: "Xtended Bitnami"
  price: "10"
  priceCurrency: "EUR"
  ticketsNumber: "50"
  buyButtonLink: "https://www.ticketea.com/androidxtended/"
  buyButtonText: "Comprar"
  additionalInfo: ""
  featured: true
  ticketContentList: ["Accede a todas las charlas y talleres en la Sede de Bitnami", "Consulta la agenda para ver los cambios", "Solo 50 plazas!!!!"]
  validFrom: "2015-04-29T20:00"
  validThrough: "2015-05-12T23:59"
  disabled: false
  soldOut: false
  soldOutText: "Agotadas!"

# Footer
socialLinks:
 - {link: "https://plus.google.com/117186888160178861350/about", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGSevilla", icon: "twitter"}
 - {link: "https://www.facebook.com/pages/Sevilla-GDG/198294916872055", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Enlaces"
  links:
   - {link: "https://plus.google.com/117186888160178861350/", text: "GDG Sevilla"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contactar"
  links:
   - {link: "mailto:contacto@androidXtended.com", text: "contacto@androidXtended.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de Conducta"}

# Blog
blogTitle: "Últimas noticias"
blogCommentsEnabled: false
discusShortName: "AndroidXtended"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "El Equipo"
aboutUs: "Creemos firmemente que la mejor forma de aprender y estar al día en esta profesión tan cambiante es compartir. Y como la mejor manera de predicar es con el ejemplo, tratamos de organizar al menos un evento
al mes sobre temas relacionados con la industria. Si estas son cosas que resuenan contigo, eres mas que bienvenido a formar parte de este equipo."

# Logistics Find Way Block
findWayTitle: "Cómo llegar"
findWayDistance: "Distancia"
findWayDriving: "En Coche"
findWayWalking: "Andando"
findWayBicycling: "En Bicicleta"
findWayTransit: "Autobus"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "judges.jpg"
directionDetailsTitle: "Qué necesito?"
directionDetailsCards:
 - {title: "Entrada", information: 'Sin esto, las dos replicas gigantes del robot de Android que hemos instalado en la entrada no te dejaran pasar. Consigue la <a href="https://www.ticketea
 .com/androidxtended/">tuya</a> antes de que se agoten.'}
 - {title: "Portátil", information: 'Los talleres son parte del evento y no se simultanean con ninguna charla. Si quieres sacarle el máximo provecho a la experencia no te lo dejes en casa.'}

hackathonPlaceCoordinates: ""
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"

